spring:
  application:
    name: nttdata-taller-microservicios-eureka
server:
  port: 8761
eureka:
  server:
    enable-self-preservation: false
  client:
    #telling the server not to register himself in the service registry
    registerWithEureka: false
    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka