spring:
  application:
    name: nttdata-taller-microservicios-schools
  cloud:
    config:
      import-check:
        enabled: false
server:
  port: 9080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
